# Generated by Django 6.0.5 on 2026-05-23 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('unit', models.IntegerField()),
                ('level', models.CharField(choices=[('100L', '100 Level'), ('200L', '200 Level'), ('300L', '300 Level'), ('400L', '400 Level'), ('500L', '500 Level')], default='100L', max_length=4)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.department')),
            ],
        ),
    ]
