# Generated by Django 6.0.5 on 2026-05-23 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_venue_department_alter_venue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.faculty'),
        ),
    ]
