# Generated by Django 6.1 on 2026-08-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_academicsession_constraintsetting_timeslot_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lectureravailability',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lectureravailability',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='lectureravailability',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='sessionslot',
            name='lecturer',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('TIMETABLE_OFFICER', 'Timetable Officer'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
        migrations.DeleteModel(
            name='AdjustmentRequest',
        ),
        migrations.DeleteModel(
            name='LecturerAvailability',
        ),
    ]
