# Generated by Django 6.0.6 on 2026-08-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_alter_lectureravailability_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='officer_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='venue',
            name='officer_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('TIMETABLE_OFFICER', 'Timetable Officer'), ('DEPARTMENT', 'Department'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
