# Generated by Django 6.1 on 2026-08-19 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_course_officer_note_course_status_venue_officer_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_practical',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('100L', '100 Level'), ('200L', '200 Level'), ('300L', '300 Level'), ('400L', '400 Level'), ('500L', '500 Level')], max_length=4)),
                ('scheme', models.CharField(choices=[('GENERAL', 'General Group'), ('COURSE_SPECIFIC', 'Course-Specific Group'), ('PRACTICAL', 'Practical Group')], max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('departments', models.ManyToManyField(blank=True, related_name='student_groups', to='scheduler.department')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='student_groups',
            field=models.ManyToManyField(blank=True, related_name='courses', to='scheduler.studentgroup'),
        ),
        migrations.AddField(
            model_name='sessionslot',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_slots', to='scheduler.studentgroup'),
        ),
    ]
