import React, { useState, useEffect } from 'react';
import API from '../api/client';
import TimetableGrid from '../components/TimetableGrid';
import { exportTimetablePdf } from '../utils/exportPdf';

const TABS = ['TIMETABLE', 'COURSES', 'VENUES', 'GROUPS', 'PENDING REVIEW'];
const STATUS_COLORS = {
  PENDING: 'bg-amber-50 text-amber-600',
  APPROVED: 'bg-green-50 text-green-600',
  REJECTED: 'bg-red-50 text-red-600',
};
const LEVELS = ['100L', '200L', '300L', '400L', '500L'];
const SCHEMES = [
  { value: 'GENERAL', label: 'General Group' },
  { value: 'COURSE_SPECIFIC', label: 'Course-Specific Group' },
  { value: 'PRACTICAL', label: 'Practical Group' },
];

export default function OfficerDashboard() {
  const [tab, setTab] = useState('TIMETABLE');
  const [schedules, setSchedules] = useState([]);
  const [courses, setCourses] = useState([]);
  const [venues, setVenues] = useState([]);
  const [cohorts, setCohorts] = useState([]);
  const [departments, setDepartments] = useState([]);
  const [groups, setGroups] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [generating, setGenerating] = useState(false);
  const [openAssign, setOpenAssign] = useState(null);
  const [assignSelections, setAssignSelections] = useState({});

  const [courseForm, setCourseForm] = useState({
    code: '', title: '', unit: 2,
    department: '',
    selectedCohorts: [],
    hasPractical: false,
  });
  const [venueForm, setVenueForm] = useState({ name: '', capacity: '' });
  const [groupForm, setGroupForm] = useState({
    level: '100L', scheme: 'GENERAL', name: '', selectedDepartments: [],
  });

  const fetchAll = async () => {
    setLoading(true);
    try {
      const [slotsRes, coursesRes, venuesRes, cohortsRes, deptsRes, groupsRes] = await Promise.all([
        API.get('slots/'),
        API.get('courses/'),
        API.get('venues/'),
        API.get('cohorts/'),
        API.get('departments/'),
        API.get('groups/'),
      ]);
      setSchedules(slotsRes.data.map(slot => ({
        course_code: (slot.course_detail || '').split(' - ')[0] || `ID:${slot.course}`,
        room: slot.venue_name || 'TBD',
        day: (slot.day || 'MON').toUpperCase().substring(0, 3),
        start_time: slot.start_time ? slot.start_time.substring(0, 5) : '08:00',
        duration: parseInt(slot.duration || 1, 10),
      })));
      setCourses(coursesRes.data);
      setVenues(venuesRes.data);
      setCohorts(cohortsRes.data);
      setDepartments(deptsRes.data);
      setGroups(groupsRes.data);
    } catch (e) {
      setError('Failed to load data');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchAll(); }, []);

  const msg = (ok, text) => {
    if (ok) setSuccess(text); else setError(text);
    setTimeout(() => { setSuccess(''); setError(''); }, 4000);
  };

  const handleGenerate = async () => {
    if (!window.confirm('Generate new timetable? Current slots will be replaced.')) return;
    setGenerating(true);
    try {
      const res = await API.post('generate/', { initial_temperature: 1000.0, cooling_rate: 0.95, min_temperature: 0.01 });
      msg(true, `Generated. Conflicts: ${res.data.hard_conflicts}. Sessions: ${res.data.sessions_generated}`);
      await fetchAll();
    } catch (e) {
      msg(false, e.response?.data?.error || 'Generation failed');
    } finally {
      setGenerating(false);
    }
  };

  const handleExport = () => {
    exportTimetablePdf(schedules, {
      title: 'Faculty of Science — Academic Timetable',
      subtitle: 'Generated by Timetable Officer Dashboard',
      filename: 'faculty-timetable'
    });
  };

  const handlePublish = async () => {
    if (!window.confirm('Publish timetable? It will be visible to all users.')) return;
    try {
      const res = await API.post('publish/');
      msg(true, `Published ${res.data.slots_published} slots`);
    } catch (e) {
      msg(false, 'Publish failed');
    }
  };

  const toggleCohort = (id) => {
    setCourseForm(f => ({
      ...f,
      selectedCohorts: f.selectedCohorts.includes(id)
        ? f.selectedCohorts.filter(c => c !== id)
        : [...f.selectedCohorts, id]
    }));
  };

  const handleCreateCourse = async (e) => {
    e.preventDefault();
    if (courseForm.selectedCohorts.length === 0) {
      msg(false, 'Select at least one cohort');
      return;
    }
    try {
      await API.post('courses/', {
        code: courseForm.code,
        title: courseForm.title,
        unit: parseInt(courseForm.unit),
        department: courseForm.department ? parseInt(courseForm.department) : null,
        cohorts: courseForm.selectedCohorts,
        has_practical: courseForm.hasPractical,
      });
      msg(true, 'Course created');
      setCourseForm({ code: '', title: '', unit: 2, department: '', selectedCohorts: [], hasPractical: false });
      fetchAll();
    } catch (e) {
      msg(false, e.response?.data?.code?.[0] || JSON.stringify(e.response?.data) || 'Failed to create course');
    }
  };

  const handleDeleteCourse = async (id) => {
    if (!window.confirm('Delete this course?')) return;
    try {
      await API.delete(`courses/${id}/`);
      msg(true, 'Deleted');
      fetchAll();
    } catch (e) {
      msg(false, 'Delete failed');
    }
  };

  const handleCreateVenue = async (e) => {
    e.preventDefault();
    try {
      await API.post('venues/', { name: venueForm.name, capacity: parseInt(venueForm.capacity) });
      msg(true, 'Venue created');
      setVenueForm({ name: '', capacity: '' });
      fetchAll();
    } catch (e) {
      msg(false, e.response?.data?.name?.[0] || 'Failed to create venue');
    }
  };

  const handleDeleteVenue = async (id) => {
    if (!window.confirm('Delete this venue?')) return;
    try {
      await API.delete(`venues/${id}/`);
      msg(true, 'Deleted');
      fetchAll();
    } catch (e) {
      msg(false, 'Delete failed — venue may be in use');
    }
  };

  const handleImportCSV = async (e, endpoint) => {
    const file = e.target.files[0];
    if (!file) return;
    const formData = new FormData();
    formData.append('file', file);
    try {
      const res = await API.post(endpoint, formData, { headers: { 'Content-Type': 'multipart/form-data' } });
      msg(true, `Imported ${res.data.created_or_updated}. Errors: ${res.data.errors.length}`);
      if (res.data.errors.length > 0) console.warn(res.data.errors);
      fetchAll();
    } catch (e) {
      msg(false, 'Import failed');
    }
    e.target.value = '';
  };

  const handleReviewCourse = async (id, decision) => {
    const note = decision === 'REJECTED' ? (window.prompt('Rejection note (optional):') || '') : '';
    try {
      await API.post(`courses/${id}/review/`, { decision, note });
      msg(true, `Course ${decision.toLowerCase()}`);
      fetchAll();
    } catch (e) {
      msg(false, 'Review failed');
    }
  };

  const handleReviewVenue = async (id, decision) => {
    const note = decision === 'REJECTED' ? (window.prompt('Rejection note (optional):') || '') : '';
    try {
      await API.post(`venues/${id}/review/`, { decision, note });
      msg(true, `Venue ${decision.toLowerCase()}`);
      fetchAll();
    } catch (e) {
      msg(false, 'Review failed');
    }
  };

  const toggleGroupDepartment = (id) => {
    setGroupForm(f => ({
      ...f,
      selectedDepartments: f.selectedDepartments.includes(id)
        ? f.selectedDepartments.filter(d => d !== id)
        : [...f.selectedDepartments, id]
    }));
  };

  const handleCreateGroup = async (e) => {
    e.preventDefault();
    if (!groupForm.name.trim()) {
      msg(false, 'Group name is required (e.g. A, B, 1, 2)');
      return;
    }
    if (groupForm.selectedDepartments.length === 0) {
      msg(false, 'Select at least one department for this group');
      return;
    }
    try {
      await API.post('groups/', {
        level: groupForm.level,
        scheme: groupForm.scheme,
        name: groupForm.name.trim(),
        departments: groupForm.selectedDepartments,
      });
      msg(true, 'Group created');
      setGroupForm({ level: '100L', scheme: 'GENERAL', name: '', selectedDepartments: [] });
      fetchAll();
    } catch (e) {
      msg(false, 'Failed to create group');
    }
  };

  const handleDeleteGroup = async (id) => {
    if (!window.confirm('Delete this group? Courses linked to it will lose this grouping.')) return;
    try {
      await API.delete(`groups/${id}/`);
      msg(true, 'Group deleted');
      fetchAll();
    } catch (e) {
      msg(false, 'Delete failed');
    }
  };

  const openAssignPanel = (course) => {
    if (openAssign === course.id) {
      setOpenAssign(null);
      return;
    }
    setAssignSelections(s => ({
      ...s,
      [course.id]: (course.student_groups_detail || []).map(g => g.id)
    }));
    setOpenAssign(course.id);
  };

  const toggleAssignGroup = (courseId, groupId) => {
    setAssignSelections(s => {
      const current = s[courseId] || [];
      return {
        ...s,
        [courseId]: current.includes(groupId)
          ? current.filter(g => g !== groupId)
          : [...current, groupId]
      };
    });
  };

  const handleSaveGroupAssignment = async (courseId) => {
    try {
      await API.patch(`courses/${courseId}/`, {
        student_groups: assignSelections[courseId] || []
      });
      msg(true, 'Groups updated for course');
      setOpenAssign(null);
      fetchAll();
    } catch (e) {
      msg(false, 'Failed to update groups');
    }
  };

  const handleLogout = () => { localStorage.removeItem('token'); window.location.href = '/login'; };

  const pendingCourses = courses.filter(c => c.status === 'PENDING');
  const pendingVenues = venues.filter(v => v.status === 'PENDING');

  return (
    <div className="min-h-screen bg-slate-50 font-mono">
      <div className="bg-white border-b border-slate-200 px-4 py-3 flex justify-between items-center">
        <div>
          <h1 className="text-sm font-bold text-slate-900">TIMETABLE OFFICER</h1>
          <p className="text-[10px] text-slate-400">Faculty of Science — GSU</p>
        </div>
        <div className="flex gap-2">
          <button onClick={handleGenerate} disabled={generating}
            className="px-3 py-1.5 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded disabled:opacity-50">
            {generating ? 'GENERATING...' : 'GENERATE'}
          </button>
          <button onClick={handleExport}
            className="px-3 py-1.5 bg-slate-700 hover:bg-slate-600 text-white text-xs font-bold rounded">
            EXPORT PDF
          </button>
          <button onClick={handlePublish}
            className="px-3 py-1.5 bg-green-600 hover:bg-green-700 text-white text-xs font-bold rounded">
            PUBLISH
          </button>
          <button onClick={handleLogout}
            className="px-3 py-1.5 border border-red-200 text-red-600 text-xs font-bold rounded">
            LOGOUT
          </button>
        </div>
      </div>

      <div className="flex border-b border-slate-200 bg-white px-4 overflow-x-auto">
        {TABS.map(t => (
          <button key={t} onClick={() => setTab(t)}
            className={`px-4 py-2 text-[11px] font-bold border-b-2 whitespace-nowrap transition-colors ${tab === t ? 'border-blue-600 text-blue-600' : 'border-transparent text-slate-400 hover:text-slate-600'}`}>
            {t}{t === 'PENDING REVIEW' && (pendingCourses.length + pendingVenues.length) > 0 ? ` (${pendingCourses.length + pendingVenues.length})` : ''}
          </button>
        ))}
      </div>

      <div className="p-4">
        {error && <div className="bg-red-50 text-red-700 text-xs p-3 rounded mb-3 border border-red-200">{error}</div>}
        {success && <div className="bg-green-50 text-green-700 text-xs p-3 rounded mb-3 border border-green-200">{success}</div>}

        {tab === 'TIMETABLE' && (
          loading
            ? <div className="text-center text-xs text-slate-400 py-12">Loading...</div>
            : <TimetableGrid schedules={schedules} />
        )}

        {tab === 'COURSES' && (
          <div className="max-w-3xl">
            <div className="bg-white border border-slate-200 rounded-lg p-4 mb-4 shadow-sm">
              <h2 className="text-xs font-bold text-slate-700 mb-3 uppercase">Add Course</h2>
              <form onSubmit={handleCreateCourse} className="space-y-3">
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-[10px] text-slate-500 mb-1">CODE</label>
                    <input value={courseForm.code} onChange={e => setCourseForm({...courseForm, code: e.target.value})} required
                      className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400" />
                  </div>
                  <div>
                    <label className="block text-[10px] text-slate-500 mb-1">TITLE</label>
                    <input value={courseForm.title} onChange={e => setCourseForm({...courseForm, title: e.target.value})} required
                      className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400" />
                  </div>
                  <div>
                    <label className="block text-[10px] text-slate-500 mb-1">UNITS</label>
                    <select value={courseForm.unit} onChange={e => setCourseForm({...courseForm, unit: e.target.value})}
                      className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400">
                      {[1,2,3].map(u => <option key={u} value={u}>{u}</option>)}
                    </select>
                  </div>
                  <div>
                    <label className="block text-[10px] text-slate-500 mb-1">DEPARTMENT</label>
                    <select value={courseForm.department} onChange={e => setCourseForm({...courseForm, department: e.target.value})}
                      className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400">
                      <option value="">-- All Departments --</option>
                      {departments.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}
                    </select>
                  </div>
                </div>

                <div>
                  <label className="block text-[10px] text-slate-500 mb-2">
                    COHORTS ({courseForm.selectedCohorts.length} selected)
                  </label>
                  <div className="border border-slate-200 rounded p-2 max-h-40 overflow-y-auto grid grid-cols-2 gap-1">
                    {cohorts.map(c => (
                      <label key={c.id} className="flex items-center gap-1.5 cursor-pointer hover:bg-slate-50 p-1 rounded">
                        <input
                          type="checkbox"
                          checked={courseForm.selectedCohorts.includes(c.id)}
                          onChange={() => toggleCohort(c.id)}
                          className="w-3 h-3"
                        />
                        <span className="text-[10px] text-slate-700">{c.department_name} {c.level}</span>
                      </label>
                    ))}
                  </div>
                </div>

                <label className="flex items-center gap-1.5 cursor-pointer">
                  <input type="checkbox" checked={courseForm.hasPractical}
                    onChange={e => setCourseForm({...courseForm, hasPractical: e.target.checked})}
                    className="w-3 h-3" />
                  <span className="text-[10px] text-slate-700">Has a practical/lab component</span>
                </label>

                <button type="submit" className="w-full py-2 bg-slate-900 text-white text-xs font-bold rounded hover:bg-slate-700">
                  ADD COURSE
                </button>
              </form>

              <div className="mt-3 pt-3 border-t border-slate-100">
                <label className="block text-[10px] text-slate-500 mb-1">
                  BULK IMPORT CSV (code, title, unit, department, cohorts)
                  <span className="text-slate-400 ml-1">— cohorts column: semicolon-separated levels e.g. 100L;200L</span>
                </label>
                <input type="file" accept=".csv" onChange={e => handleImportCSV(e, 'import/courses/')}
                  className="text-xs text-slate-600" />
              </div>
            </div>

            <div className="bg-white border border-slate-200 rounded-lg shadow-sm">
              <div className="p-3 border-b border-slate-100 text-xs font-bold text-slate-700">COURSES ({courses.length})</div>
              <div className="divide-y divide-slate-100 max-h-[32rem] overflow-y-auto">
                {courses.map(c => (
                  <div key={c.id} className="p-3">
                    <div className="flex items-center justify-between">
                      <div>
                        <div className="text-xs font-bold text-slate-800">{c.code}</div>
                        <div className="text-[10px] text-slate-500">{c.title} · {c.unit}u{c.has_practical ? ' · Practical' : ''}</div>
                        <div className="text-[10px] text-blue-500">
                          {c.cohorts_detail?.map(cd => cd.label).join(', ') || 'No cohorts'}
                        </div>
                        <div className="text-[10px] text-purple-500">
                          {c.student_groups_detail?.length > 0
                            ? `Groups: ${c.student_groups_detail.map(g => g.label).join(', ')}`
                            : 'No groups assigned'}
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        <span className={`text-[10px] font-bold px-2 py-0.5 rounded ${STATUS_COLORS[c.status] || ''}`}>{c.status}</span>
                        {c.status === 'APPROVED' && (
                          <button onClick={() => openAssignPanel(c)}
                            className="px-2 py-1 text-[10px] font-bold bg-purple-50 text-purple-600 border border-purple-200 rounded">
                            {openAssign === c.id ? 'CLOSE' : 'GROUPS'}
                          </button>
                        )}
                        <button onClick={() => handleDeleteCourse(c.id)}
                          className="px-2 py-1 text-[10px] font-bold bg-red-50 text-red-600 border border-red-200 rounded">DEL</button>
                      </div>
                    </div>

                    {openAssign === c.id && (
                      <div className="mt-2 p-2 bg-slate-50 rounded border border-slate-200">
                        <div className="text-[10px] font-bold text-slate-600 mb-1">ASSIGN GROUPS TO THIS COURSE</div>
                        {groups.length === 0 ? (
                          <div className="text-[10px] text-slate-400">No groups defined yet — create some in the GROUPS tab first</div>
                        ) : (
                          <div className="grid grid-cols-1 gap-1 max-h-32 overflow-y-auto">
                            {groups.map(g => (
                              <label key={g.id} className="flex items-center gap-1.5 cursor-pointer">
                                <input type="checkbox"
                                  checked={(assignSelections[c.id] || []).includes(g.id)}
                                  onChange={() => toggleAssignGroup(c.id, g.id)}
                                  className="w-3 h-3" />
                                <span className="text-[10px] text-slate-700">
                                  {g.level} · {SCHEMES.find(s => s.value === g.scheme)?.label || g.scheme} · {g.name}
                                  {' — '}{g.departments_detail?.map(d => d.name).join(', ')}
                                </span>
                              </label>
                            ))}
                          </div>
                        )}
                        <button onClick={() => handleSaveGroupAssignment(c.id)}
                          className="mt-2 px-3 py-1 text-[10px] font-bold bg-slate-900 text-white rounded">
                          SAVE
                        </button>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {tab === 'VENUES' && (
          <div className="max-w-xl">
            <div className="bg-white border border-slate-200 rounded-lg p-4 mb-4 shadow-sm">
              <h2 className="text-xs font-bold text-slate-700 mb-3 uppercase">Add Venue</h2>
              <form onSubmit={handleCreateVenue} className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-[10px] text-slate-500 mb-1">NAME</label>
                  <input value={venueForm.name} onChange={e => setVenueForm({...venueForm, name: e.target.value})} required
                    className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400" />
                </div>
                <div>
                  <label className="block text-[10px] text-slate-500 mb-1">CAPACITY</label>
                  <input type="number" value={venueForm.capacity} onChange={e => setVenueForm({...venueForm, capacity: e.target.value})} required
                    className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400" />
                </div>
                <div className="col-span-2">
                  <button type="submit" className="w-full py-2 bg-slate-900 text-white text-xs font-bold rounded hover:bg-slate-700">ADD VENUE</button>
                </div>
              </form>
              <div className="mt-3 pt-3 border-t border-slate-100">
                <label className="block text-[10px] text-slate-500 mb-1">BULK IMPORT CSV (name, capacity)</label>
                <input type="file" accept=".csv" onChange={e => handleImportCSV(e, 'import/venues/')}
                  className="text-xs text-slate-600" />
              </div>
            </div>
            <div className="bg-white border border-slate-200 rounded-lg shadow-sm">
              <div className="p-3 border-b border-slate-100 text-xs font-bold text-slate-700">VENUES ({venues.length})</div>
              <div className="divide-y divide-slate-100 max-h-96 overflow-y-auto">
                {venues.map(v => (
                  <div key={v.id} className="flex items-center justify-between p-3">
                    <div>
                      <div className="text-xs font-bold text-slate-800">{v.name}</div>
                      <div className="text-[10px] text-slate-500">Capacity: {v.capacity}</div>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className={`text-[10px] font-bold px-2 py-0.5 rounded ${STATUS_COLORS[v.status] || ''}`}>{v.status}</span>
                      <button onClick={() => handleDeleteVenue(v.id)}
                        className="px-2 py-1 text-[10px] font-bold bg-red-50 text-red-600 border border-red-200 rounded">DEL</button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {tab === 'GROUPS' && (
          <div className="max-w-2xl">
            <div className="bg-white border border-slate-200 rounded-lg p-4 mb-4 shadow-sm">
              <h2 className="text-xs font-bold text-slate-700 mb-3 uppercase">Create Group</h2>
              <form onSubmit={handleCreateGroup} className="space-y-3">
                <div className="grid grid-cols-3 gap-3">
                  <div>
                    <label className="block text-[10px] text-slate-500 mb-1">LEVEL</label>
                    <select value={groupForm.level} onChange={e => setGroupForm({...groupForm, level: e.target.value})}
                      className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400">
                      {LEVELS.map(l => <option key={l} value={l}>{l}</option>)}
                    </select>
                  </div>
                  <div>
                    <label className="block text-[10px] text-slate-500 mb-1">SCHEME</label>
                    <select value={groupForm.scheme} onChange={e => setGroupForm({...groupForm, scheme: e.target.value})}
                      className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400">
                      {SCHEMES.map(s => <option key={s.value} value={s.value}>{s.label}</option>)}
                    </select>
                  </div>
                  <div>
                    <label className="block text-[10px] text-slate-500 mb-1">NAME</label>
                    <input value={groupForm.name} onChange={e => setGroupForm({...groupForm, name: e.target.value})}
                      placeholder="A, B, 1, 2..." required
                      className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400" />
                  </div>
                </div>

                <div>
                  <label className="block text-[10px] text-slate-500 mb-2">
                    DEPARTMENTS IN THIS GROUP ({groupForm.selectedDepartments.length} selected)
                  </label>
                  <div className="border border-slate-200 rounded p-2 max-h-40 overflow-y-auto grid grid-cols-2 gap-1">
                    {departments.map(d => (
                      <label key={d.id} className="flex items-center gap-1.5 cursor-pointer hover:bg-slate-50 p-1 rounded">
                        <input type="checkbox"
                          checked={groupForm.selectedDepartments.includes(d.id)}
                          onChange={() => toggleGroupDepartment(d.id)}
                          className="w-3 h-3" />
                        <span className="text-[10px] text-slate-700">{d.name}</span>
                      </label>
                    ))}
                  </div>
                </div>

                <button type="submit" className="w-full py-2 bg-slate-900 text-white text-xs font-bold rounded hover:bg-slate-700">
                  CREATE GROUP
                </button>
              </form>
            </div>

            <div className="bg-white border border-slate-200 rounded-lg shadow-sm">
              <div className="p-3 border-b border-slate-100 text-xs font-bold text-slate-700">DEFINED GROUPS ({groups.length})</div>
              {groups.length === 0 ? (
                <div className="p-6 text-center text-xs text-slate-400">No groups defined yet</div>
              ) : (
                <div className="divide-y divide-slate-100 max-h-96 overflow-y-auto">
                  {groups.map(g => (
                    <div key={g.id} className="flex items-center justify-between p-3">
                      <div>
                        <div className="text-xs font-bold text-slate-800">
                          {g.level} — {SCHEMES.find(s => s.value === g.scheme)?.label || g.scheme} — {g.name}
                        </div>
                        <div className="text-[10px] text-slate-500">
                          {g.departments_detail?.map(d => d.name).join(', ') || 'No departments'}
                        </div>
                      </div>
                      <button onClick={() => handleDeleteGroup(g.id)}
                        className="px-2 py-1 text-[10px] font-bold bg-red-50 text-red-600 border border-red-200 rounded">DEL</button>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}

        {tab === 'PENDING REVIEW' && (
          <div className="max-w-3xl space-y-4">
            <div className="bg-white border border-slate-200 rounded-lg shadow-sm">
              <div className="p-3 border-b border-slate-100 text-xs font-bold text-slate-700">PENDING COURSES ({pendingCourses.length})</div>
              {pendingCourses.length === 0 ? (
                <div className="p-6 text-center text-xs text-slate-400">Nothing pending</div>
              ) : (
                <div className="divide-y divide-slate-100">
                  {pendingCourses.map(c => (
                    <div key={c.id} className="p-3">
                      <div className="flex justify-between items-start mb-2">
                        <div>
                          <div className="text-xs font-bold text-slate-800">{c.code}</div>
                          <div className="text-[10px] text-slate-500">{c.title} · {c.unit}u · {c.department_name}</div>
                        </div>
                      </div>
                      <div className="flex gap-2">
                        <button onClick={() => handleReviewCourse(c.id, 'APPROVED')}
                          className="px-3 py-1 text-[10px] font-bold bg-green-50 text-green-600 border border-green-200 rounded">APPROVE</button>
                        <button onClick={() => handleReviewCourse(c.id, 'REJECTED')}
                          className="px-3 py-1 text-[10px] font-bold bg-red-50 text-red-600 border border-red-200 rounded">REJECT</button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>

            <div className="bg-white border border-slate-200 rounded-lg shadow-sm">
              <div className="p-3 border-b border-slate-100 text-xs font-bold text-slate-700">PENDING VENUES ({pendingVenues.length})</div>
              {pendingVenues.length === 0 ? (
                <div className="p-6 text-center text-xs text-slate-400">Nothing pending</div>
              ) : (
                <div className="divide-y divide-slate-100">
                  {pendingVenues.map(v => (
                    <div key={v.id} className="p-3">
                      <div className="flex justify-between items-start mb-2">
                        <div>
                          <div className="text-xs font-bold text-slate-800">{v.name}</div>
                          <div className="text-[10px] text-slate-500">Capacity: {v.capacity} · {v.department_name}</div>
                        </div>
                      </div>
                      <div className="flex gap-2">
                        <button onClick={() => handleReviewVenue(v.id, 'APPROVED')}
                          className="px-3 py-1 text-[10px] font-bold bg-green-50 text-green-600 border border-green-200 rounded">APPROVE</button>
                        <button onClick={() => handleReviewVenue(v.id, 'REJECTED')}
                          className="px-3 py-1 text-[10px] font-bold bg-red-50 text-red-600 border border-red-200 rounded">REJECT</button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
