import React, { useState, useEffect } from 'react';
import API from '../api/client';
import TimetableGrid from '../components/TimetableGrid';
import { exportTimetablePdf } from '../utils/exportPdf';

const TABS = ['TIMETABLE', 'COURSES', 'VENUES', 'GROUPS', 'DEPARTMENTS', 'PENDING REVIEW'];
const STATUS_COLORS = {
  PENDING: 'bg-amber-50 text-amber-600',
  APPROVED: 'bg-green-50 text-green-600',
  REJECTED: 'bg-red-50 text-red-600',
};
const LEVELS = ['100L', '200L', '300L', '400L', '500L'];
const SCHEMES = [
  { value: 'GENERAL', label: 'General Group' },
  { value: 'COURSE_SPECIFIC', label: 'Course-Specific Group' },
  { value: 'PRACTICAL', label: 'Practical Group' },
];

export default function OfficerDashboard() {
  const [tab, setTab] = useState('TIMETABLE');
  const [schedules, setSchedules] = useState([]);
  const [courses, setCourses] = useState([]);
  const [venues, setVenues] = useState([]);
  const [cohorts, setCohorts] = useState([]);
  const [departments, setDepartments] = useState([]);
  const [faculties, setFaculties] = useState([]);
  const [groups, setGroups] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [generating, setGenerating] = useState(false);
  const [openAssign, setOpenAssign] = useState(null);
  const [assignSelections, setAssignSelections] = useState({});
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  const [courseForm, setCourseForm] = useState({
    code: '', title: '', unit: 2,
    department: '',
    selectedCohorts: [],
    hasPractical: false,
  });
  const [venueForm, setVenueForm] = useState({ name: '', capacity: '' });
  const [groupForm, setGroupForm] = useState({
    level: '100L', scheme: 'GENERAL', name: '', selectedDepartments: [], course: '',
  });
  const [facultyForm, setFacultyForm] = useState({ name: '', code: '' });
  const [deptForm, setDeptForm] = useState({ name: '', code: '', faculty: '' });
  const [cohortForm, setCohortForm] = useState({ department: '', level: '100L', studentCount: '' });

  const fetchAll = async () => {
    setLoading(true);
    try {
      const [slotsRes, coursesRes, venuesRes, cohortsRes, deptsRes, groupsRes, facultiesRes] = await Promise.all([
        API.get('slots/'),
        API.get('courses/'),
        API.get('venues/'),
        API.get('cohorts/'),
        API.get('departments/'),
        API.get('groups/'),
        API.get('faculties/'),
      ]);
      setSchedules(slotsRes.data.map(slot => ({
        course_code: (slot.course_detail || '').split(' - ')[0] || `ID:${slot.course}`,
        room: slot.venue_name || 'TBD',
        student_group_detail: slot.student_group_detail,
        day: (slot.day || 'MON').toUpperCase().substring(0, 3),
        start_time: slot.start_time ? slot.start_time.substring(0, 5) : '08:00',
        duration: parseInt(slot.duration || 1, 10),
      })));
      setCourses(coursesRes.data);
      setVenues(venuesRes.data);
      setCohorts(cohortsRes.data);
      setDepartments(deptsRes.data);
      setGroups(groupsRes.data);
      setFaculties(facultiesRes.data);
    } catch (e) {
      setError('Failed to load data');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchAll(); }, []);

  const msg = (ok, text) => {
    if (ok) setSuccess(text); else setError(text);
    setTimeout(() => { setSuccess(''); setError(''); }, 4000);
  };

  const handleGenerate = async () => {
    if (!window.confirm('Generate new timetable? Current slots will be replaced.')) return;
    setGenerating(true);
    try {
      const res = await API.post('generate/', { initial_temperature: 1000.0, cooling_rate: 0.95, min_temperature: 0.01 });
      msg(true, `Generated. Conflicts: ${res.data.hard_conflicts}. Sessions: ${res.data.sessions_generated}`);
      await fetchAll();
    } catch (e) {
      msg(false, e.response?.data?.error || 'Generation failed');
    } finally {
      setGenerating(false);
    }
  };

  const handleExport = () => {
    exportTimetablePdf(schedules, {
      title: 'Faculty of Science — Academic Timetable',
      subtitle: 'Generated by Timetable Officer Dashboard',
      filename: 'faculty-timetable'
    });
  };

  const handlePublish = async () => {
    if (!window.confirm('Publish timetable? It will be visible to all users.')) return;
    try {
      const res = await API.post('publish/');
      msg(true, `Published ${res.data.slots_published} slots`);
    } catch (e) {
      msg(false, 'Publish failed');
    }
  };

  // ... rest of handlers (unchanged) ...

  const toggleCohort = (id) => {
    setCourseForm(f => ({
      ...f,
      selectedCohorts: f.selectedCohorts.includes(id)
        ? f.selectedCohorts.filter(c => c !== id)
        : [...f.selectedCohorts, id]
    }));
  };

  const handleCreateCourse = async (e) => {
    e.preventDefault();
    if (courseForm.selectedCohorts.length === 0) {
      msg(false, 'Select at least one cohort');
      return;
    }
    try {
      await API.post('courses/', {
        code: courseForm.code,
        title: courseForm.title,
        unit: parseInt(courseForm.unit),
        department: courseForm.department ? parseInt(courseForm.department) : null,
        cohorts: courseForm.selectedCohorts,
        has_practical: courseForm.hasPractical,
      });
      msg(true, 'Course created');
      setCourseForm({ code: '', title: '', unit: 2, department: '', selectedCohorts: [], hasPractical: false });
      fetchAll();
    } catch (e) {
      msg(false, e.response?.data?.code?.[0] || JSON.stringify(e.response?.data) || 'Failed to create course');
    }
  };

  const handleDeleteCourse = async (id) => {
    if (!window.confirm('Delete this course?')) return;
    try {
      await API.delete(`courses/${id}/`);
      msg(true, 'Deleted');
      fetchAll();
    } catch (e) {
      msg(false, 'Delete failed');
    }
  };

  const handleCreateVenue = async (e) => {
    e.preventDefault();
    try {
      await API.post('venues/', { name: venueForm.name, capacity: parseInt(venueForm.capacity) });
      msg(true, 'Venue created');
      setVenueForm({ name: '', capacity: '' });
      fetchAll();
    } catch (e) {
      msg(false, e.response?.data?.name?.[0] || 'Failed to create venue');
    }
  };

  const handleDeleteVenue = async (id) => {
    if (!window.confirm('Delete this venue?')) return;
    try {
      await API.delete(`venues/${id}/`);
      msg(true, 'Deleted');
      fetchAll();
    } catch (e) {
      msg(false, 'Delete failed — venue may be in use');
    }
  };

  const handleImportCSV = async (e, endpoint) => {
    const file = e.target.files[0];
    if (!file) return;
    const formData = new FormData();
    formData.append('file', file);
    try {
      const res = await API.post(endpoint, formData, { headers: { 'Content-Type': 'multipart/form-data' } });
      msg(true, `Imported ${res.data.created_or_updated}. Errors: ${res.data.errors.length}`);
      if (res.data.errors.length > 0) console.warn(res.data.errors);
      fetchAll();
    } catch (e) {
      msg(false, 'Import failed');
    }
    e.target.value = '';
  };

  const handleReviewCourse = async (id, decision) => {
    const note = decision === 'REJECTED' ? (window.prompt('Rejection note (optional):') || '') : '';
    try {
      await API.post(`courses/${id}/review/`, { decision, note });
      msg(true, `Course ${decision.toLowerCase()}`);
      fetchAll();
    } catch (e) {
      msg(false, 'Review failed');
    }
  };

  const handleReviewVenue = async (id, decision) => {
    const note = decision === 'REJECTED' ? (window.prompt('Rejection note (optional):') || '') : '';
    try {
      await API.post(`venues/${id}/review/`, { decision, note });
      msg(true, `Venue ${decision.toLowerCase()}`);
      fetchAll();
    } catch (e) {
      msg(false, 'Review failed');
    }
  };

  const toggleGroupDepartment = (id) => {
    setGroupForm(f => ({
      ...f,
      selectedDepartments: f.selectedDepartments.includes(id)
        ? f.selectedDepartments.filter(d => d !== id)
        : [...f.selectedDepartments, id]
    }));
  };

  const handleCreateGroup = async (e) => {
    e.preventDefault();
    if (!groupForm.name.trim()) {
      msg(false, 'Group name is required (e.g. A, B, 1, 2)');
      return;
    }
    if (groupForm.selectedDepartments.length === 0) {
      msg(false, 'Select at least one department for this group');
      return;
    }
    if (groupForm.scheme === 'COURSE_SPECIFIC' && !groupForm.course) {
      msg(false, 'Select the course this group belongs to');
      return;
    }
    try {
      const res = await API.post('groups/', {
        level: groupForm.level,
        scheme: groupForm.scheme,
        name: groupForm.name.trim(),
        departments: groupForm.selectedDepartments,
      });
      if (groupForm.scheme === 'COURSE_SPECIFIC' && groupForm.course) {
        const course = courses.find(c => c.id === parseInt(groupForm.course));
        const existingGroupIds = (course?.student_groups_detail || []).map(g => g.id);
        await API.patch(`courses/${groupForm.course}/`, {
          student_groups: [...existingGroupIds, res.data.id]
        });
      }
      msg(true, groupForm.scheme === 'COURSE_SPECIFIC' ? 'Group created and assigned to course' : 'Group created');
      setGroupForm({ level: '100L', scheme: 'GENERAL', name: '', selectedDepartments: [], course: '' });
      fetchAll();
    } catch (e) {
      msg(false, 'Failed to create group');
    }
  };

  const handleDeleteGroup = async (id) => {
    if (!window.confirm('Delete this group? Courses linked to it will lose this grouping.')) return;
    try {
      await API.delete(`groups/${id}/`);
      msg(true, 'Group deleted');
      fetchAll();
    } catch (e) {
      msg(false, 'Delete failed');
    }
  };

  const handleCreateFaculty = async (e) => {
    e.preventDefault();
    try {
      await API.post('faculties/', { name: facultyForm.name, code: facultyForm.code });
      msg(true, 'Faculty created');
      setFacultyForm({ name: '', code: '' });
      fetchAll();
    } catch (e) {
      msg(false, e.response?.data?.name?.[0] || e.response?.data?.code?.[0] || 'Failed to create faculty');
    }
  };

  const handleCreateDepartment = async (e) => {
    e.preventDefault();
    if (!deptForm.faculty) {
      msg(false, 'Select a faculty for this department');
      return;
    }
    try {
      await API.post('departments/', {
        name: deptForm.name,
        code: deptForm.code,
        faculty: parseInt(deptForm.faculty),
      });
      msg(true, 'Department created');
      setDeptForm({ name: '', code: '', faculty: '' });
      fetchAll();
    } catch (e) {
      msg(false, e.response?.data?.name?.[0] || e.response?.data?.code?.[0] || 'Failed to create department');
    }
  };

  const handleCreateCohort = async (e) => {
    e.preventDefault();
    if (!cohortForm.department) {
      msg(false, 'Select a department for this cohort');
      return;
    }
    try {
      await API.post('cohorts/', {
        department: parseInt(cohortForm.department),
        level: cohortForm.level,
        student_count: cohortForm.studentCount ? parseInt(cohortForm.studentCount) : 0,
      });
      msg(true, 'Cohort created');
      setCohortForm({ department: '', level: '100L', studentCount: '' });
      fetchAll();
    } catch (e) {
      msg(false, e.response?.data?.non_field_errors?.[0] || 'Failed to create cohort — it may already exist for this department/level');
    }
  };

  const openAssignPanel = (course) => {
    if (openAssign === course.id) {
      setOpenAssign(null);
      return;
    }
    setAssignSelections(s => ({
      ...s,
      [course.id]: (course.student_groups_detail || []).map(g => g.id)
    }));
    setOpenAssign(course.id);
  };

  const toggleAssignGroup = (courseId, groupId) => {
    setAssignSelections(s => {
      const current = s[courseId] || [];
      return {
        ...s,
        [courseId]: current.includes(groupId)
          ? current.filter(g => g !== groupId)
          : [...current, groupId]
      };
    });
  };

  const handleSaveGroupAssignment = async (courseId) => {
    try {
      await API.patch(`courses/${courseId}/`, {
        student_groups: assignSelections[courseId] || []
      });
      msg(true, 'Groups updated for course');
      setOpenAssign(null);
      fetchAll();
    } catch (e) {
      msg(false, 'Failed to update groups');
    }
  };

  const handleLogout = () => { localStorage.removeItem('token'); window.location.href = '/login'; };

  const pendingCourses = courses.filter(c => c.status === 'PENDING');
  const pendingVenues = venues.filter(v => v.status === 'PENDING');

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Row 1: Title + Logout */}
      <div className="bg-white border-b border-slate-200 px-4 py-3">
        <div className="max-w-7xl mx-auto flex flex-wrap items-center justify-between gap-2">
          <div>
            <h1 className="text-sm font-bold text-slate-900">TIMETABLE OFFICER</h1>
            <p className="text-[10px] sm:text-xs text-slate-400">Faculty of Science — GSU</p>
          </div>
          <button onClick={handleLogout}
            className="px-3 py-1.5 border border-red-300 hover:bg-red-50 text-red-600 text-xs font-bold rounded transition-colors">
            LOGOUT
          </button>
        </div>
      </div>

      {/* Row 2: Action Buttons – horizontal scroll on mobile, wrap on desktop */}
      <div className="bg-white border-b border-slate-200 px-4 py-2">
        <div className="max-w-7xl mx-auto flex flex-nowrap sm:flex-wrap items-center gap-1 sm:gap-2 overflow-x-auto">
          <button onClick={handleGenerate} disabled={generating}
            className="px-3 py-1.5 text-[10px] sm:text-xs font-bold bg-blue-600 hover:bg-blue-700 text-white rounded transition-colors disabled:opacity-50 whitespace-nowrap">
            {generating ? 'GENERATING...' : 'GENERATE'}
          </button>
          <button onClick={handleExport}
            className="px-3 py-1.5 text-[10px] sm:text-xs font-bold border border-slate-300 hover:bg-slate-50 text-slate-700 rounded transition-colors whitespace-nowrap">
            EXPORT PDF
          </button>
          <button onClick={handlePublish}
            className="px-3 py-1.5 text-[10px] sm:text-xs font-bold bg-green-600 hover:bg-green-700 text-white rounded transition-colors whitespace-nowrap">
            PUBLISH
          </button>
        </div>
      </div>

      {/* Row 3: Tabs – hidden on mobile (hamburger only), visible on desktop */}
      <div className="border-b border-slate-200 bg-white px-4">
        <div className="max-w-7xl mx-auto py-1">
          {/* Hamburger (mobile only) */}
          <div className="md:hidden flex items-center justify-between">
            <button 
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
              className="text-slate-600 hover:text-slate-800 text-xl font-bold px-2 py-1"
            >
              ☰
            </button>
            <span className="text-xs font-bold text-slate-400">
              {tab} {pendingCourses.length + pendingVenues.length > 0 && tab === 'PENDING REVIEW' ? `(${pendingCourses.length + pendingVenues.length})` : ''}
            </span>
          </div>

          {/* Tabs list – hidden on mobile unless open, flex on desktop */}
          <div className={`${mobileMenuOpen ? 'block' : 'hidden'} md:flex flex-nowrap items-center gap-1 overflow-x-auto`}>
            {TABS.map(t => (
              <button key={t} onClick={() => { setTab(t); setMobileMenuOpen(false); }}
                className={`px-3 py-2 text-[10px] sm:text-xs font-bold border-b-2 whitespace-nowrap transition-colors ${
                  tab === t ? 'border-blue-600 text-blue-600' : 'border-transparent text-slate-400 hover:text-slate-600'
                }`}>
                {t}{t === 'PENDING REVIEW' && (pendingCourses.length + pendingVenues.length) > 0 ? ` (${pendingCourses.length + pendingVenues.length})` : ''}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Main content */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 md:py-6">
        {error && <div className="bg-red-50 text-red-700 text-xs p-3 rounded mb-3 border border-red-200">{error}</div>}
        {success && <div className="bg-green-50 text-green-700 text-xs p-3 rounded mb-3 border border-green-200">{success}</div>}

        {tab === 'TIMETABLE' && (
          loading
            ? <div className="text-center text-xs text-slate-400 py-12">Loading...</div>
            : <div className="overflow-x-auto"><TimetableGrid schedules={schedules} /></div>
        )}

        {/* ... rest of tabs (COURSES, VENUES, etc.) unchanged ... */}
        {tab === 'COURSES' && (
          <div>
            <div className="bg-white border border-slate-200 rounded-lg p-4 md:p-6 mb-4 shadow-sm">
              <h2 className="text-xs font-bold text-slate-700 mb-3 uppercase">Add Course</h2>
              <form onSubmit={handleCreateCourse} className="space-y-3">
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
                  <div>
                    <label className="block text-xs text-slate-500 mb-1">CODE</label>
                    <input value={courseForm.code} onChange={e => setCourseForm({...courseForm, code: e.target.value})} required
                      className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400" />
                  </div>
                  <div>
                    <label className="block text-xs text-slate-500 mb-1">TITLE</label>
                    <input value={courseForm.title} onChange={e => setCourseForm({...courseForm, title: e.target.value})} required
                      className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400" />
                  </div>
                  <div>
                    <label className="block text-xs text-slate-500 mb-1">UNITS</label>
                    <select value={courseForm.unit} onChange={e => setCourseForm({...courseForm, unit: e.target.value})}
                      className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400">
                      {[1,2,3].map(u => <option key={u} value={u}>{u}</option>)}
                    </select>
                  </div>
                  <div>
                    <label className="block text-xs text-slate-500 mb-1">DEPARTMENT</label>
                    <select value={courseForm.department} onChange={e => setCourseForm({...courseForm, department: e.target.value})}
                      className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400">
                      <option value="">-- All Departments --</option>
                      {departments.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}
                    </select>
                  </div>
                  <div className="lg:col-span-2">
                    <label className="block text-xs text-slate-500 mb-2">
                      COHORTS ({courseForm.selectedCohorts.length} selected)
                    </label>
                    <div className="border border-slate-200 rounded p-2 max-h-40 overflow-y-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-1">
                      {cohorts.map(c => (
                        <label key={c.id} className="flex items-center gap-1.5 cursor-pointer hover:bg-slate-50 p-1 rounded">
                          <input
                            type="checkbox"
                            checked={courseForm.selectedCohorts.includes(c.id)}
                            onChange={() => toggleCohort(c.id)}
                            className="w-3 h-3"
                          />
                          <span className="text-[10px] sm:text-xs text-slate-700">{c.department_name} {c.level}</span>
                        </label>
                      ))}
                    </div>
                  </div>
                  <div className="flex items-center">
                    <label className="flex items-center gap-1.5 cursor-pointer">
                      <input type="checkbox" checked={courseForm.hasPractical}
                        onChange={e => setCourseForm({...courseForm, hasPractical: e.target.checked})}
                        className="w-3 h-3" />
                      <span className="text-xs text-slate-700">Has practical/lab</span>
                    </label>
                  </div>
                </div>

                <button type="submit" className="w-full py-2 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded transition-colors">
                  ADD COURSE
                </button>
              </form>

              <div className="mt-3 pt-3 border-t border-slate-100">
                <label className="block text-xs text-slate-500 mb-1">
                  BULK IMPORT CSV (code, title, unit, department, cohorts)
                  <span className="text-slate-400 ml-1">— cohorts column: semicolon-separated levels e.g. 100L;200L</span>
                </label>
                <input type="file" accept=".csv" onChange={e => handleImportCSV(e, 'import/courses/')}
                  className="text-xs text-slate-600 w-full sm:w-auto" />
              </div>
            </div>

            <div className="bg-white border border-slate-200 rounded-lg shadow-sm">
              <div className="p-3 border-b border-slate-100 text-xs font-bold text-slate-700">COURSES ({courses.length})</div>
              <div className="divide-y divide-slate-100 max-h-[32rem] overflow-y-auto">
                {courses.map(c => (
                  <div key={c.id} className="p-3 md:p-4">
                    <div className="flex flex-col md:flex-row md:items-center justify-between gap-2">
                      <div>
                        <div className="text-xs font-bold text-slate-800">{c.code}</div>
                        <div className="text-[10px] sm:text-xs text-slate-500">{c.title} · {c.unit}u{c.has_practical ? ' · Practical' : ''}</div>
                        <div className="text-[10px] sm:text-xs text-blue-500">
                          {c.cohorts_detail?.map(cd => cd.label).join(', ') || 'No cohorts'}
                        </div>
                        <div className="text-[10px] sm:text-xs text-purple-500">
                          {c.student_groups_detail?.length > 0
                            ? `Groups: ${c.student_groups_detail.map(g => g.label).join(', ')}`
                            : 'No groups assigned'}
                        </div>
                      </div>
                      <div className="flex flex-wrap items-center gap-2">
                        <span className={`text-[10px] font-bold px-2 py-0.5 rounded ${STATUS_COLORS[c.status] || ''}`}>{c.status}</span>
                        {c.status === 'APPROVED' && (
                          <button onClick={() => openAssignPanel(c)}
                            className="px-2 py-1 text-[10px] font-bold border border-slate-300 hover:bg-slate-50 text-slate-700 rounded transition-colors">
                            {openAssign === c.id ? 'CLOSE' : 'GROUPS'}
                          </button>
                        )}
                        <button onClick={() => handleDeleteCourse(c.id)}
                          className="px-2 py-1 text-[10px] font-bold border border-red-300 hover:bg-red-50 text-red-600 rounded transition-colors">
                          DEL
                        </button>
                      </div>
                    </div>

                    {openAssign === c.id && (
                      <div className="mt-2 p-2 bg-slate-50 rounded border border-slate-200">
                        <div className="text-[10px] font-bold text-slate-600 mb-1">ASSIGN GROUPS TO THIS COURSE</div>
                        {groups.length === 0 ? (
                          <div className="text-[10px] text-slate-400">No groups defined yet — create some in the GROUPS tab first</div>
                        ) : (
                          <div className="grid grid-cols-1 gap-1 max-h-32 overflow-y-auto">
                            {groups.map(g => (
                              <label key={g.id} className="flex items-center gap-1.5 cursor-pointer">
                                <input type="checkbox"
                                  checked={(assignSelections[c.id] || []).includes(g.id)}
                                  onChange={() => toggleAssignGroup(c.id, g.id)}
                                  className="w-3 h-3" />
                                <span className="text-[10px] sm:text-xs text-slate-700">
                                  {g.level} · {SCHEMES.find(s => s.value === g.scheme)?.label || g.scheme} · {g.name}
                                  {' — '}{g.departments_detail?.map(d => d.name).join(', ')}
                                </span>
                              </label>
                            ))}
                          </div>
                        )}
                        <button onClick={() => handleSaveGroupAssignment(c.id)}
                          className="mt-2 px-3 py-1 text-[10px] font-bold bg-blue-600 hover:bg-blue-700 text-white rounded transition-colors">
                          SAVE
                        </button>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {tab === 'VENUES' && (
          <div>
            <div className="bg-white border border-slate-200 rounded-lg p-4 md:p-6 mb-4 shadow-sm">
              <h2 className="text-xs font-bold text-slate-700 mb-3 uppercase">Add Venue</h2>
              <form onSubmit={handleCreateVenue} className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs text-slate-500 mb-1">NAME</label>
                  <input value={venueForm.name} onChange={e => setVenueForm({...venueForm, name: e.target.value})} required
                    className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400" />
                </div>
                <div>
                  <label className="block text-xs text-slate-500 mb-1">CAPACITY</label>
                  <input type="number" value={venueForm.capacity} onChange={e => setVenueForm({...venueForm, capacity: e.target.value})} required
                    className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400" />
                </div>
                <div className="col-span-1 sm:col-span-2">
                  <button type="submit" className="w-full py-2 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded transition-colors">
                    ADD VENUE
                  </button>
                </div>
              </form>
              <div className="mt-3 pt-3 border-t border-slate-100">
                <label className="block text-xs text-slate-500 mb-1">BULK IMPORT CSV (name, capacity)</label>
                <input type="file" accept=".csv" onChange={e => handleImportCSV(e, 'import/venues/')}
                  className="text-xs text-slate-600 w-full sm:w-auto" />
              </div>
            </div>
            <div className="bg-white border border-slate-200 rounded-lg shadow-sm">
              <div className="p-3 border-b border-slate-100 text-xs font-bold text-slate-700">VENUES ({venues.length})</div>
              <div className="divide-y divide-slate-100 max-h-96 overflow-y-auto">
                {venues.map(v => (
                  <div key={v.id} className="flex flex-col sm:flex-row sm:items-center justify-between p-3 md:p-4 gap-2">
                    <div>
                      <div className="text-xs font-bold text-slate-800">{v.name}</div>
                      <div className="text-[10px] sm:text-xs text-slate-500">Capacity: {v.capacity}</div>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className={`text-[10px] font-bold px-2 py-0.5 rounded ${STATUS_COLORS[v.status] || ''}`}>{v.status}</span>
                      <button onClick={() => handleDeleteVenue(v.id)}
                        className="px-2 py-1 text-[10px] font-bold border border-red-300 hover:bg-red-50 text-red-600 rounded transition-colors">
                        DEL
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}


                {tab === 'GROUPS' && (
          <div>
            <div className="bg-white border border-slate-200 rounded-lg p-4 md:p-6 mb-4 shadow-sm">
              <h2 className="text-xs font-bold text-slate-700 mb-3 uppercase">Create Group</h2>
              <form onSubmit={handleCreateGroup} className="space-y-3">
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
                  <div>
                    <label className="block text-xs text-slate-500 mb-1">LEVEL</label>
                    <select value={groupForm.level} onChange={e => setGroupForm({...groupForm, level: e.target.value})}
                      className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400">
                      {LEVELS.map(l => <option key={l} value={l}>{l}</option>)}
                    </select>
                  </div>
                  <div>
                    <label className="block text-xs text-slate-500 mb-1">SCHEME</label>
                    <select value={groupForm.scheme} onChange={e => setGroupForm({...groupForm, scheme: e.target.value, course: ''})}
                      className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400">
                      {SCHEMES.map(s => <option key={s.value} value={s.value}>{s.label}</option>)}
                    </select>
                  </div>
                  <div>
                    <label className="block text-xs text-slate-500 mb-1">NAME</label>
                    <input value={groupForm.name} onChange={e => setGroupForm({...groupForm, name: e.target.value})}
                      placeholder="A, B, 1, 2..." required
                      className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400" />
                  </div>
                </div>

                {groupForm.scheme === 'COURSE_SPECIFIC' && (
                  <div>
                    <label className="block text-xs text-slate-500 mb-1">COURSE (required)</label>
                    <select value={groupForm.course} onChange={e => setGroupForm({...groupForm, course: e.target.value})}
                      className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400">
                      <option value="">-- Select Course --</option>
                      {courses.filter(c => c.status === 'APPROVED').map(c => (
                        <option key={c.id} value={c.id}>{c.code} - {c.title}</option>
                      ))}
                    </select>
                    {courses.filter(c => c.status === 'APPROVED').length === 0 && (
                      <div className="text-[10px] text-amber-600 mt-1">No approved courses yet — approve a course first in PENDING REVIEW</div>
                    )}
                  </div>
                )}

                <div>
                  <label className="block text-xs text-slate-500 mb-2">
                    DEPARTMENTS IN THIS GROUP ({groupForm.selectedDepartments.length} selected)
                  </label>
                  <div className="border border-slate-200 rounded p-2 max-h-40 overflow-y-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-1">
                    {departments.map(d => (
                      <label key={d.id} className="flex items-center gap-1.5 cursor-pointer hover:bg-slate-50 p-1 rounded">
                        <input type="checkbox"
                          checked={groupForm.selectedDepartments.includes(d.id)}
                          onChange={() => toggleGroupDepartment(d.id)}
                          className="w-3 h-3" />
                        <span className="text-[10px] sm:text-xs text-slate-700">{d.name}</span>
                      </label>
                    ))}
                  </div>
                </div>

                <button type="submit" className="w-full py-2 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded transition-colors">
                  CREATE GROUP
                </button>
              </form>

              {/* ─── NEW BULK IMPORT BOX ─── */}
              <div className="mt-3 pt-3 border-t border-slate-100">
                <label className="block text-xs text-slate-500 mb-1 font-medium">
                  BULK IMPORT GROUPS VIA CSV (scheme, name, level, course_code, departments)
                </label>
                <input 
                  type="file" 
                  accept=".csv" 
                  onChange={(e) => handleImportCSV(e, 'import/groups/')} 
                  className="text-xs text-slate-600 w-full sm:w-auto mt-1 cursor-pointer" 
                />
              </div>
            </div>

            <div className="bg-white border border-slate-200 rounded-lg shadow-sm">
              <div className="p-3 border-b border-slate-100 text-xs font-bold text-slate-700">DEFINED GROUPS ({groups.length})</div>
              {groups.length === 0 ? (
                <div className="p-6 text-center text-xs text-slate-400">No groups defined yet</div>
              ) : (
                <div className="divide-y divide-slate-100 max-h-96 overflow-y-auto">
                  {groups.map(g => (
                    <div key={g.id} className="flex flex-col sm:flex-row sm:items-center justify-between p-3 md:p-4 gap-2">
                      <div>
                        <div className="text-xs font-bold text-slate-800">
                          {g.level} — {SCHEMES.find(s => s.value === g.scheme)?.label || g.scheme} — {g.name}
                        </div>
                        <div className="text-[10px] sm:text-xs text-slate-500">
                          {g.departments_detail?.map(d => d.name).join(', ') || 'No departments'}
                        </div>
                      </div>
                      <button onClick={() => handleDeleteGroup(g.id)}
                        className="px-2 py-1 text-[10px] font-bold border border-red-300 hover:bg-red-50 text-red-600 rounded transition-colors">
                        DEL
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}

                {tab === 'DEPARTMENTS' && (
          <div className="space-y-4">
            {/* 1. Add Faculty Section Card */}
            <div className="bg-white border border-slate-200 rounded-lg p-4 md:p-6 shadow-sm">
              <h2 className="text-xs font-bold text-slate-700 mb-3 uppercase">Add Faculty</h2>
              <form onSubmit={handleCreateFaculty} className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs text-slate-500 mb-1">NAME</label>
                  <input 
                    value={facultyForm.name} 
                    onChange={e => setFacultyForm({...facultyForm, name: e.target.value})} 
                    required
                    className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400" 
                  />
                </div>
                <div>
                  <label className="block text-xs text-slate-500 mb-1">CODE</label>
                  <input 
                    value={facultyForm.code} 
                    onChange={e => setFacultyForm({...facultyForm, code: e.target.value})} 
                    required
                    className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400" 
                  />
                </div>
                <div className="col-span-1 sm:col-span-2">
                  <button type="submit" className="w-full py-2 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded transition-colors">
                    ADD FACULTY
                  </button>
                </div>
              </form>

              {/* Bulk Import Faculties CSV Box Element */}
              <div className="mt-3 pt-3 border-t border-slate-100">
                <label className="block text-xs text-slate-500 mb-1 font-medium">
                  BULK IMPORT FACULTIES CSV (name, code)
                </label>
                <input 
                  type="file" 
                  accept=".csv" 
                  onChange={(e) => handleImportCSV(e, 'import/faculties/')} 
                  className="text-xs text-slate-600 w-full sm:w-auto mt-1 cursor-pointer" 
                />
              </div>

              <div className="mt-3 pt-3 border-t border-slate-100 text-xs text-slate-500">
                {faculties.length} faculties loaded
                {faculties.length > 0 && (
                  <div className="mt-1 text-slate-400">{faculties.map(f => `${f.name} (${f.code})`).join(', ')}</div>
                )}
              </div>
            </div>

            {/* 2. Add Department Section Card */}
            <div className="bg-white border border-slate-200 rounded-lg p-4 md:p-6 shadow-sm">
              <h2 className="text-xs font-bold text-slate-700 mb-3 uppercase">Add Department</h2>
              <form onSubmit={handleCreateDepartment} className="space-y-3">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <div>
                    <label className="block text-xs text-slate-500 mb-1">NAME</label>
                    <input 
                      value={deptForm.name} 
                      onChange={e => setDeptForm({...deptForm, name: e.target.value})} 
                      required
                      className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400" 
                    />
                  </div>
                  <div>
                    <label className="block text-xs text-slate-500 mb-1">CODE</label>
                    <input 
                      value={deptForm.code} 
                      onChange={e => setDeptForm({...deptForm, code: e.target.value})} 
                      required
                      className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400" 
                    />
                  </div>
                </div>
                <div>
                  <label className="block text-xs text-slate-500 mb-1">FACULTY</label>
                  <select 
                    value={deptForm.faculty} 
                    onChange={e => setDeptForm({...deptForm, faculty: e.target.value})} 
                    required
                    className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400"
                  >
                    <option value="">-- Select Faculty --</option>
                    {faculties.map(f => <option key={f.id} value={f.id}>{f.name}</option>)}
                  </select>
                </div>
                <button type="submit" className="w-full py-2 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded transition-colors">
                  ADD DEPARTMENT
                </button>
              </form>
              <div className="mt-3 pt-3 border-t border-slate-100">
                <label className="block text-xs text-slate-500 mb-1 font-medium">BULK IMPORT DEPARTMENTS CSV (name, code, faculty)</label>
                <input 
                  type="file" 
                  accept=".csv" 
                  onChange={e => handleImportCSV(e, 'import/departments/')} 
                  className="text-xs text-slate-600 w-full sm:w-auto mt-1 cursor-pointer" 
                />
                <div className="mt-2 text-xs text-slate-500">{departments.length} departments loaded</div>
              </div>
            </div>

            {/* 3. Add Cohort Section Card */}
            <div className="bg-white border border-slate-200 rounded-lg p-4 md:p-6 shadow-sm">
              <h2 className="text-xs font-bold text-slate-700 mb-3 uppercase">Add Cohort</h2>
              <form onSubmit={handleCreateCohort} className="space-y-3">
                <div>
                  <label className="block text-xs text-slate-500 mb-1">DEPARTMENT</label>
                  <select 
                    value={cohortForm.department} 
                    onChange={e => setCohortForm({...cohortForm, department: e.target.value})} 
                    required
                    className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400"
                  >
                    <option value="">-- Select Department --</option>
                    {departments.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}
                  </select>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <div>
                    <label className="block text-xs text-slate-500 mb-1">LEVEL</label>
                    <select 
                      value={cohortForm.level} 
                      onChange={e => setCohortForm({...cohortForm, level: e.target.value})}
                      className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400"
                    >
                      {LEVELS.map(l => <option key={l} value={l}>{l}</option>)}
                    </select>
                  </div>
                  <div>
                    <label className="block text-xs text-slate-500 mb-1">STUDENT COUNT</label>
                    <input 
                      type="number" 
                      value={cohortForm.studentCount} 
                      onChange={e => setCohortForm({...cohortForm, studentCount: e.target.value})}
                      placeholder="e.g. 80"
                      className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-slate-400" 
                    />
                  </div>
                </div>
                <button type="submit" className="w-full py-2 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded transition-colors">
                  ADD COHORT
                </button>
              </form>
              <div className="mt-3 pt-3 border-t border-slate-100">
                <label className="block text-xs text-slate-500 mb-1 font-medium">BULK IMPORT COHORTS CSV (department, level, student_count)</label>
                <input 
                  type="file" 
                  accept=".csv" 
                  onChange={e => handleImportCSV(e, 'import/cohorts/')} 
                  className="text-xs text-slate-600 w-full sm:w-auto mt-1 cursor-pointer" 
                />
                <div className="mt-3 pt-3 border-t border-slate-100 text-xs text-slate-500">{cohorts.length} cohorts loaded</div>
              </div>
            </div>
          </div>
        )}


        {tab === 'PENDING REVIEW' && (
          <div className="space-y-4">
            <div className="bg-white border border-slate-200 rounded-lg shadow-sm">
              <div className="p-3 border-b border-slate-100 text-xs font-bold text-slate-700">PENDING COURSES ({pendingCourses.length})</div>
              {pendingCourses.length === 0 ? (
                <div className="p-6 text-center text-xs text-slate-400">Nothing pending</div>
              ) : (
                <div className="divide-y divide-slate-100">
                  {pendingCourses.map(c => (
                    <div key={c.id} className="p-3 md:p-4">
                      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-2">
                        <div>
                          <div className="text-xs font-bold text-slate-800">{c.code}</div>
                          <div className="text-[10px] sm:text-xs text-slate-500">{c.title} · {c.unit}u · {c.department_name}</div>
                        </div>
                        <div className="flex gap-2">
                          <button onClick={() => handleReviewCourse(c.id, 'APPROVED')}
                            className="px-3 py-1 text-[10px] font-bold bg-green-600 hover:bg-green-700 text-white rounded transition-colors">
                            APPROVE
                          </button>
                          <button onClick={() => handleReviewCourse(c.id, 'REJECTED')}
                            className="px-3 py-1 text-[10px] font-bold bg-red-600 hover:bg-red-700 text-white rounded transition-colors">
                            REJECT
                          </button>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>

            <div className="bg-white border border-slate-200 rounded-lg shadow-sm">
              <div className="p-3 border-b border-slate-100 text-xs font-bold text-slate-700">PENDING VENUES ({pendingVenues.length})</div>
              {pendingVenues.length === 0 ? (
                <div className="p-6 text-center text-xs text-slate-400">Nothing pending</div>
              ) : (
                <div className="divide-y divide-slate-100">
                  {pendingVenues.map(v => (
                    <div key={v.id} className="p-3 md:p-4">
                      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-2">
                        <div>
                          <div className="text-xs font-bold text-slate-800">{v.name}</div>
                          <div className="text-[10px] sm:text-xs text-slate-500">Capacity: {v.capacity} · {v.department_name}</div>
                        </div>
                        <div className="flex gap-2">
                          <button onClick={() => handleReviewVenue(v.id, 'APPROVED')}
                            className="px-3 py-1 text-[10px] font-bold bg-green-600 hover:bg-green-700 text-white rounded transition-colors">
                            APPROVE
                          </button>
                          <button onClick={() => handleReviewVenue(v.id, 'REJECTED')}
                            className="px-3 py-1 text-[10px] font-bold bg-red-600 hover:bg-red-700 text-white rounded transition-colors">
                            REJECT
                          </button>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
